baseURL = "https://powerfam.github.io/"
languageCode = "ko-kr"
title = "Voti's Blog"
theme = "PaperMod"

[params]
  description = "Life, Feeling, Thinking"
  author = "powerfam"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  
  [params.homeInfoParams]
    Title = "Voti's Blog"
    Content = "Life, Feeling, Thinking"

  [params.profileMode]
    enabled = true
    title = "Voti's Blog"
    subtitle = "Life, Feeling, Thinking"
    imageUrl = "images/green.png"
    imageWidth = 300
    imageHeight = 300
    imageTitle = "Profile"

[[menu.main]]
  name = "Papa's Letter"
  url = "/letter/"
  weight = 10

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 20

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 30

[[params.socialIcons]]
  name = "email"
  url = "mailto:powerfam@naver.com"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/changhan-lee-83a797116/"

[[params.socialIcons]]
  name = "instagram"
  url = "https://www.instagram.com/changssan16"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      hardWraps = true
