baseURL = "/"
languageCode = "ko-kr"
title = "Voti's Blog"
theme = "PaperMod"

[params]
  description = "Life, Feeling, Thinking"
  author = "powerfam"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  
  # profileMode 대신 이거 시도
  homeInfoParams.Title = "Voti's Blog"
  homeInfoParams.Content = "Life, Feeling, Thinking"
<<<<<<< HEAD
  
  # 아바타 이미지
  avatar = "/images/green.png"

  [params.profileMode]
    enabled = true
    title = "Voti's Blog"
    subtitle = "Life, Feeling, Thinking"
    imageUrl = "https://github.com/powerfam/powerfam.github.io/blob/main/static/images/green.png?raw=true"
    imageWidth = 300
    imageHeight = 300
    imageTitle = "Profile"

[[menu.main]]
  name = "Papa's Letter"
  url = "/letter/"
  weight = 10

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 20

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 30

[[params.socialIcons]]
  name = "email"
  url = "mailto:powerfam@naver.com"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/changhan-lee-83a797116/"

[[params.socialIcons]]
  name = "instagram"
  url = "https://www.instagram.com/changssan16"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      hardWraps = true
